M1 day 4 dev task theja
IshaaqhShaik/ROR_Nov pull request #15
Opened 2024-12-02 21:25 UTC by Thejuhoney

create new branch
add notes in task file 
and staged the file and commit the file 
and push the changes to the branch

2024-12-02 21:27 UTC, Thejuhoney commented
changes to the day3 task and cheetsheet
please review my pr

2024-12-03 12:58 UTC, IshaaqhShaik requested changes
Commit history is corrupt.

2024-12-03 13:40 UTC, Thejuhoney commented
> Please clean the commit history there multiple adhoc commits from several dev's

updated commit history as per requested

2024-12-04 13:58 UTC, IshaaqhShaik approved these changes

2024-12-04 13:58 UTC, merged