Interview questions
IshaaqhShaik/ROR_Nov pull request #7
Opened 2024-11-28 14:06 UTC by Thejuhoney

updated interview questions for Day 3

2024-11-28 15:51 UTC, IshaaqhShaik requested changes
Please move the changes to cheatsheet

2024-12-02 19:11 UTC, Thejuhoney reviewed
day 1 and 2 presentation notes updated in task file and interview questions updated in cheetsheet

2024-12-03 12:54 UTC, IshaaqhShaik commented
Please resolve the merge conflicts and clean the commit history as well there are multiple commits from multiple developers.

2024-12-04 11:43 UTC, Kunimohan commented
> Please resolve the merge conflicts and clean the commit history as well there are multiple commits from multiple developers


resolved merge conflicts and updated commits

2024-12-04 13:40 UTC, IshaaqhShaik requested changes

2024-12-04 13:40 UTC, IshaaqhShaik commented on Module-1/Day-3/Cheatsheet/cheatsheet.txt
> +Q1 what is git
Please indent and name the questions accordingly

2024-12-04 13:55 UTC, IshaaqhShaik approved these changes

2024-12-04 13:56 UTC, merged